### ISSUE TITLE
question on the result

### ISSUE THREAD

**Issue by Eavis** [petermlm/SobelFilter#2]
Hi there, thanks for providing the implementation. 
However, when I cd src and make it, 
I run the command line "./sobel file_in.png  file_out.png 123x456 "
It will generate a file but cannot be opened and there is no error information.

Would you know if there is any solution to it?

**Comment by petermlm** [comment]
Good morning.

Sorry on my late answer. This program only takes images in the RGB format and outputs images in the GREY format. The specification for both formats is [here](https://imagemagick.org/script/formats.php).

If you have a png image, you can use Image Magick to convert you initial image to RGB, use the SobelFilter program, and use Image Magick again to convert the outputed GREY file to png so you can see it the results. Image Magick is used with the `convert` command, like so:

```
convert file_in.png file_in.rgb
./sobel file_in.rgb file_out.gray 512x512
convert -size 512x512 -depth 8 file_out.gray file_out.png
```

Please notice that the values `512x512` should be the size of your image.

As it stands the SobelFilter program is not very user friendly, since the user needs to use an external tool (Image Magick) to work with it. I should develop this a bit further.

**Comment by Eavis** [comment]
Thank you very much for the response!

Pedro Melgueira <notifications@github.com> 于2018年10月8日周一 上午4:11写道：

**Comment by petermlm** [comment]
Anytime! Thank you for taking interesting in this project!

Best regards,
Pedro Melgueira.
